import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// French translations
const fr = {
  // Header
  "nav.about": "À Propos",
  "nav.concepts": "Concepts",
  "nav.governance": "Gouvernance",
  "nav.implementation": "Implémentation",
  "nav.collaboration": "Collaboration",
  "nav.assessment": "Évaluation",
  "nav.contact": "Contact",
  "nav.backHome": "Retour à l'accueil",
  
  // Hero Section
  "hero.badge": "Transformation Organisationnelle par l'IA",
  "hero.title1": "Concevoir des organisations où",
  "hero.title2": "humains et IA pilotent ensemble la performance",
  "hero.subtitle": "en moins de 12 mois",
  "hero.description": "Augmentez votre productivité de 30%, accélérez vos décisions stratégiques, réduisez vos risques opérationnels et développez une capacité d'expérimentation continue grâce à notre framework d'organisations agentiques.",
  "hero.cta1": "Évaluer la maturité agentique de mon organisation (5 min)",
  "hero.cta2": "Découvrir le framework agentique",
  
  // Concepts Section
  "concepts.title": "Six Concepts Fondateurs",
  "concepts.description": "Un cadre conceptuel complet pour comprendre et implémenter la transformation vers une Organisation Agentique.",
  "concepts.ao.title": "Organisation Agentique (AO)",
  "concepts.ao.description": "Structure organisationnelle où les agents IA autonomes collaborent avec les humains pour atteindre des objectifs communs.",
  "concepts.ao.plain": "En clair, cela permet de transformer votre organisation en un réseau intelligent où chaque décision est augmentée par l'IA, tout en gardant l'humain au centre.",
  "concepts.at.title": "Équipe Agentique (AT)",
  "concepts.at.description": "Unité de travail combinant agents humains et IA avec des rôles complémentaires et une coordination fluide.",
  "concepts.at.plain": "En clair, cela permet à une équipe humaine d'être augmentée par des agents IA qui préparent les analyses, exécutent des tâches répétitives et laissent les humains se concentrer sur les décisions importantes.",
  "concepts.amo.title": "Mode Opératoire Agentique (AMO)",
  "concepts.amo.description": "Protocoles et processus standardisés pour la collaboration efficace entre humains et agents IA.",
  "concepts.amo.plain": "En clair, cela permet d'établir des règles du jeu claires pour que humains et IA travaillent ensemble sans friction, avec des processus bien définis.",
  "concepts.saife.title": "Cadre SAIFE",
  "concepts.saife.description": "Framework de gouvernance pour la Sécurité, l'Alignement, l'Interopérabilité, la Fiabilité et l'Éthique.",
  "concepts.saife.plain": "En clair, cela permet de garantir que vos agents IA sont sécurisés, alignés sur vos valeurs, compatibles avec vos systèmes, fiables et éthiques.",
  "concepts.hs.title": "Compétences Humaniques (HS)",
  "concepts.hs.description": "Compétences distinctement humaines essentielles dans un environnement de travail augmenté par l'IA.",
  "concepts.hs.plain": "En clair, cela permet de valoriser et développer les compétences que seuls les humains possèdent : créativité, empathie, jugement éthique et collaboration complexe.",
  "concepts.mao.title": "Organisation Agentique Minimale (MAO)",
  "concepts.mao.description": "Unité autonome de type startup pour expérimenter les principes agentiques de manière contrôlée.",
  "concepts.mao.plain": "En clair, cela permet de tester la transformation agentique dans une zone sécurisée de votre organisation avant de la déployer à grande échelle.",
  "concepts.level.strategic": "Stratégique",
  "concepts.level.network": "Réseau",
  "concepts.level.agent": "Agent",
  
  // Governance Section
  "governance.title": "Architecture de Gouvernance Multi-Niveaux",
  "governance.description": "Une structure de gouvernance intégrée assurant cohérence, responsabilité et adaptabilité à tous les niveaux.",
  "governance.strategic.title": "Gouvernance Stratégique",
  "governance.strategic.description": "Définition de la vision, des politiques globales et de l'alignement avec les objectifs organisationnels.",
  "governance.strategic.item1": "Vision et mission agentique",
  "governance.strategic.item2": "Politiques d'IA responsable",
  "governance.strategic.item3": "Allocation des ressources",
  "governance.strategic.item4": "Gestion des risques stratégiques",
  "governance.strategic.example": "Exemple: Lancement d'un nouveau produit coordonné entre R&D, Marketing et Ventes avec agents IA analysant les feedbacks clients en temps réel.",
  "governance.network.title": "Gouvernance de Réseau",
  "governance.network.description": "Coordination des interactions entre équipes agentiques et gestion des flux d'information.",
  "governance.network.item1": "Protocoles d'interopérabilité",
  "governance.network.item2": "Standards de communication",
  "governance.network.item3": "Mécanismes de coordination",
  "governance.network.item4": "Résolution des conflits",
  "governance.network.example": "Exemple: Coordination d'une gestion d'incident majeur où des agents IA IT, Communication et Support collaborent avec les équipes humaines pour résoudre et communiquer.",
  "governance.agent.title": "Gouvernance d'Agent",
  "governance.agent.description": "Règles et contraintes pour le comportement individuel des agents IA et humains.",
  "governance.agent.item1": "Limites d'autonomie",
  "governance.agent.item2": "Critères de décision",
  "governance.agent.item3": "Mécanismes de supervision",
  "governance.agent.item4": "Protocoles d'escalade",
  "governance.agent.example": "Exemple: Un agent IA de service client traite automatiquement les demandes simples mais escalade vers un humain quand l'émotion du client est détectée ou la situation dépasse son autonomie.",
  
  // Implementation Section
  "implementation.title": "Stratégie d'Implémentation en Trois Phases",
  "implementation.description": "Une feuille de route structurée pour transformer progressivement votre organisation vers un modèle agentique.",
  "implementation.phase1.title": "Fondations",
  "implementation.phase1.duration": "1-3 ans",
  "implementation.phase1.description": "Établir l'infrastructure technologique et culturelle nécessaire à la transformation.",
  "implementation.phase1.item1": "Évaluation de la préparation organisationnelle",
  "implementation.phase1.item2": "Développement des cadres de gouvernance",
  "implementation.phase1.item3": "Formation et sensibilisation des équipes",
  "implementation.phase1.item4": "Sélection des projets pilotes",
  "implementation.phase2.title": "Pilote",
  "implementation.phase2.duration": "3-7 ans",
  "implementation.phase2.description": "Implémenter des systèmes agentiques à portée limitée et itérer basé sur les retours.",
  "implementation.phase2.item1": "Déploiement de la MAO",
  "implementation.phase2.item2": "Formation d'équipes interfonctionnelles",
  "implementation.phase2.item3": "Mise en place de systèmes de suivi",
  "implementation.phase2.item4": "Collecte et analyse des retours",
  "implementation.phase3.title": "Déploiement",
  "implementation.phase3.duration": "7-10 ans",
  "implementation.phase3.description": "Étendre les capacités agentiques à l'ensemble de l'organisation.",
  "implementation.phase3.item1": "Expansion organisationnelle",
  "implementation.phase3.item2": "Durcissement de la gouvernance",
  "implementation.phase3.item3": "Optimisation continue",
  "implementation.phase3.item4": "Adaptation et évolution",
  
  // MAO Section
  "mao.badge": "Approche Progressive",
  "mao.title": "L'Organisation Agentique Minimale (MAO)",
  "mao.description": "La MAO est une unité autonome de type startup opérant comme un laboratoire expérimental au sein de l'organisation mère. Elle permet de tester les principes agentiques contre des contraintes organisationnelles réalistes.",
  "mao.feature1.title": "Fonctions Complètes",
  "mao.feature1.description": "RH, Finance, Opérations, Marketing, Stratégie intégrés",
  "mao.feature2.title": "Focus Stratégique",
  "mao.feature2.description": "Trois processus commerciaux clés à valeur mesurable",
  "mao.feature3.title": "Approche Agile",
  "mao.feature3.description": "Non-disruptive, itérative et adaptative",
  "mao.cta": "Évaluer votre préparation",
  "mao.benefits": "Avantages de la MAO",
  "mao.autonomy": "Autonomie opérationnelle",
  "mao.risk": "Risque organisationnel",
  "mao.learning": "Potentiel d'apprentissage",
  "mao.processes": "Processus clés ciblés",
  
  // Collaboration Section
  "collaboration.title": "Spectre de Collaboration Humain-IA",
  "collaboration.description": "Les quatre piliers de l'intelligence collaborative pour une synergie optimale entre humains et agents IA.",
  "collaboration.modes": "Modes de Collaboration",
  "collaboration.humanLed": "Humain-Led",
  "collaboration.humanLed.description": "L'humain dirige, l'IA assiste et amplifie",
  "collaboration.humanLed.example": "Ex: Manager analysant un dashboard IA avant de prendre une décision stratégique",
  "collaboration.peerToPeer": "Pair-à-Pair",
  "collaboration.peerToPeer.description": "Collaboration équilibrée et complémentaire",
  "collaboration.peerToPeer.example": "Ex: Chef de projet co-construisant un planning avec un agent IA d'optimisation",
  "collaboration.aiLed": "IA-Led",
  "collaboration.aiLed.description": "L'IA dirige, l'humain supervise et valide",
  "collaboration.aiLed.example": "Ex: Agent IA proposant un plan logistique optimisé que l'humain valide ou ajuste",
  "collaboration.pillar1.title": "Prise de Décision Distribuée",
  "collaboration.pillar1.description": "Pouvoir décisionnel basé sur la compétence et le contexte, non sur la hiérarchie.",
  "collaboration.pillar2.title": "Gouvernance Adaptative",
  "collaboration.pillar2.description": "Modes de gouvernance flexibles qui évoluent avec les besoins organisationnels.",
  "collaboration.pillar3.title": "Collaboration Fluide",
  "collaboration.pillar3.description": "Interaction transparente entre humains et IA avec des protocoles standardisés.",
  "collaboration.pillar4.title": "Apprentissage Continu",
  "collaboration.pillar4.description": "Adaptation et évolution organisationnelle permanentes basées sur les retours.",
  
  // CTA Section
  "cta.title": "Prêt à Transformer Votre Organisation ?",
  "cta.description": "Évaluez la maturité agentique de votre organisation et obtenez des recommandations personnalisées pour votre transformation.",
  "cta.button1": "Commencer l'évaluation",
  "cta.button2": "Demander une consultation",
  
  // Footer
  "footer.description": "Transformation organisationnelle par l'intelligence agentique.",
  "footer.concepts": "Concepts",
  "footer.resources": "Ressources",
  "footer.contact": "Contact",
  "footer.sixConcepts": "Six Concepts Fondateurs",
  "footer.multiLevelGovernance": "Gouvernance Multi-Niveaux",
  "footer.mao": "Organisation Agentique Minimale",
  "footer.implementationStrategy": "Stratégie d'Implémentation",
  "footer.humanAICollaboration": "Collaboration Humain-IA",
  "footer.assessmentTool": "Outil d'Évaluation",
  "footer.requestConsultation": "Demander une consultation",
  "footer.contactUs": "Nous contacter",
  "footer.copyright": "© 2025 AgenticOrg. Tous droits réservés.",
  
  // Assessment Page
  "assessment.question": "Question",
  "assessment.of": "sur",
  "assessment.completed": "complété",
  "assessment.previous": "Précédent",
  "assessment.next": "Suivant",
  "assessment.seeResults": "Voir les résultats",
  "assessment.results.title": "Résultats de votre Évaluation",
  "assessment.results.subtitle": "Score global de maturité agentique",
  "assessment.results.level": "Niveau",
  "assessment.results.categoryTitle": "Analyse par Catégorie",
  "assessment.results.categorySubtitle": "Détail de votre maturité dans chaque domaine",
  "assessment.results.recommendationsTitle": "Recommandations Personnalisées",
  "assessment.results.recommendationsSubtitle": "Actions prioritaires pour votre transformation",
  "assessment.results.restart": "Refaire l'évaluation",
  "assessment.results.consultation": "Demander une consultation",
  "assessment.level.beginner": "Débutant",
  "assessment.level.emerging": "Émergent",
  "assessment.level.progressing": "En Progression",
  "assessment.level.advanced": "Avancé",
  "assessment.level.beginner.description": "Votre organisation est au début de son parcours vers la transformation agentique. Des fondations importantes doivent être établies.",
  "assessment.level.emerging.description": "Votre organisation a commencé sa transformation mais doit renforcer ses fondations pour progresser efficacement.",
  "assessment.level.progressing.description": "Votre organisation progresse bien vers la maturité agentique. Focus sur l'expansion et l'optimisation.",
  "assessment.level.advanced.description": "Votre organisation est bien positionnée pour une transformation agentique complète.",
  "assessment.category.culture": "Culture Organisationnelle",
  "assessment.category.tech": "Infrastructure Technologique",
  "assessment.category.governance": "Gouvernance",
  "assessment.category.skills": "Compétences",
  "assessment.category.collaboration": "Collaboration",
  "assessment.q1": "Comment votre organisation perçoit-elle l'intelligence artificielle ?",
  "assessment.q1.o1": "Comme une menace pour l'emploi",
  "assessment.q1.o2": "Comme un outil technique parmi d'autres",
  "assessment.q1.o3": "Comme un partenaire potentiel pour améliorer la productivité",
  "assessment.q1.o4": "Comme un collaborateur stratégique pour la transformation",
  "assessment.q2": "Quel est le niveau d'ouverture au changement dans votre organisation ?",
  "assessment.q2.o1": "Résistance forte au changement",
  "assessment.q2.o2": "Acceptation passive des changements imposés",
  "assessment.q2.o3": "Adaptation proactive aux nouvelles méthodes",
  "assessment.q2.o4": "Culture d'innovation et d'expérimentation continue",
  "assessment.q3": "Quel est l'état de votre infrastructure technologique actuelle ?",
  "assessment.q3.o1": "Systèmes legacy isolés et peu intégrés",
  "assessment.q3.o2": "Infrastructure partiellement modernisée",
  "assessment.q3.o3": "Infrastructure cloud avec APIs et intégrations",
  "assessment.q3.o4": "Architecture moderne, scalable et prête pour l'IA",
  "assessment.q4": "Comment gérez-vous vos données organisationnelles ?",
  "assessment.q4.o1": "Données dispersées et non structurées",
  "assessment.q4.o2": "Quelques bases de données centralisées",
  "assessment.q4.o3": "Data warehouse avec gouvernance de base",
  "assessment.q4.o4": "Data platform unifiée avec gouvernance mature",
  "assessment.q5": "Avez-vous des politiques de gouvernance pour l'IA ?",
  "assessment.q5.o1": "Aucune politique en place",
  "assessment.q5.o2": "Quelques directives informelles",
  "assessment.q5.o3": "Politiques documentées en cours de déploiement",
  "assessment.q5.o4": "Framework de gouvernance IA complet et appliqué",
  "assessment.q6": "Comment sont prises les décisions stratégiques dans votre organisation ?",
  "assessment.q6.o1": "Décisions centralisées au sommet uniquement",
  "assessment.q6.o2": "Délégation limitée avec validation hiérarchique",
  "assessment.q6.o3": "Décisions distribuées avec cadre de gouvernance",
  "assessment.q6.o4": "Prise de décision adaptative basée sur les compétences",
  "assessment.q7": "Quel est le niveau de compétences IA dans votre organisation ?",
  "assessment.q7.o1": "Très peu de compétences IA disponibles",
  "assessment.q7.o2": "Quelques experts isolés",
  "assessment.q7.o3": "Équipes IA dédiées et programmes de formation",
  "assessment.q7.o4": "Compétences IA intégrées à tous les niveaux",
  "assessment.q8": "Comment développez-vous les compétences humaniques (créativité, empathie, jugement) ?",
  "assessment.q8.o1": "Pas de focus particulier sur ces compétences",
  "assessment.q8.o2": "Formations ponctuelles disponibles",
  "assessment.q8.o3": "Programmes structurés de développement",
  "assessment.q8.o4": "Culture d'apprentissage continu et valorisation explicite",
  "assessment.q9": "Comment collaborent actuellement vos équipes avec des outils IA ?",
  "assessment.q9.o1": "Utilisation minimale ou inexistante",
  "assessment.q9.o2": "Utilisation individuelle et non coordonnée",
  "assessment.q9.o3": "Processus définis pour certaines tâches",
  "assessment.q9.o4": "Collaboration Humain-IA intégrée aux workflows",
  "assessment.q10": "Avez-vous expérimenté des projets pilotes impliquant l'IA ?",
  "assessment.q10.o1": "Aucun projet pilote",
  "assessment.q10.o2": "Quelques expérimentations isolées",
  "assessment.q10.o3": "Projets pilotes structurés avec retours d'expérience",
  "assessment.q10.o4": "Programme d'innovation continue avec scaling des succès",
  
  // Contact Page
  "contact.title": "Demander une Consultation",
  "contact.description": "Nos experts vous accompagnent dans votre transformation vers une Organisation Agentique. Remplissez le formulaire ci-dessous pour être contacté.",
  "contact.whyTitle": "Pourquoi nous contacter ?",
  "contact.reason1.title": "Diagnostic personnalisé",
  "contact.reason1.description": "Analyse approfondie de votre organisation",
  "contact.reason2.title": "Feuille de route",
  "contact.reason2.description": "Plan d'action adapté à vos objectifs",
  "contact.reason3.title": "Accompagnement expert",
  "contact.reason3.description": "Support continu dans votre transformation",
  "contact.guarantee.title": "Réponse rapide garantie",
  "contact.guarantee.description": "Notre équipe s'engage à vous répondre dans les 24-48 heures ouvrées pour planifier un premier échange.",
  "contact.form.title": "Formulaire de Contact",
  "contact.form.required": "Tous les champs marqués d'un * sont obligatoires",
  "contact.form.name": "Nom complet",
  "contact.form.email": "Email professionnel",
  "contact.form.company": "Entreprise",
  "contact.form.role": "Fonction",
  "contact.form.interest": "Sujet d'intérêt",
  "contact.form.message": "Message",
  "contact.form.submit": "Envoyer ma demande",
  "contact.form.sending": "Envoi en cours...",
  "contact.form.selectSubject": "Sélectionnez un sujet",
  "contact.form.interest.diagnostic": "Diagnostic de maturité agentique",
  "contact.form.interest.strategy": "Stratégie de transformation",
  "contact.form.interest.mao": "Mise en place d'une MAO",
  "contact.form.interest.governance": "Gouvernance IA",
  "contact.form.interest.training": "Formation des équipes",
  "contact.form.interest.other": "Autre",
  "contact.form.namePlaceholder": "Jean Dupont",
  "contact.form.emailPlaceholder": "jean.dupont@entreprise.com",
  "contact.form.companyPlaceholder": "Nom de votre entreprise",
  "contact.form.rolePlaceholder": "Directeur / Manager / etc.",
  "contact.form.messagePlaceholder": "Décrivez brièvement votre projet ou vos questions...",
  "contact.success.title": "Demande Envoyée !",
  "contact.success.description": "Merci pour votre intérêt. Notre équipe vous contactera dans les 24-48 heures.",
  "contact.success.cta": "En attendant, vous pouvez explorer notre outil d'évaluation pour mieux comprendre la maturité agentique de votre organisation.",
  "contact.success.assessment": "Faire l'évaluation",
  "contact.error.required": "Veuillez remplir tous les champs obligatoires",
  "contact.error.generic": "Une erreur est survenue. Veuillez réessayer.",
  "contact.success.toast": "Votre demande a été envoyée avec succès !",
  "assessment.saved": "Résultats sauvegardés avec succès",
  
  // How to Work Section
  "howToWork.title": "Comment Travailler Avec Nous ?",
  "howToWork.description": "Une approche structurée en trois étapes pour transformer votre organisation",
  "howToWork.step1.title": "Comprendre le Framework",
  "howToWork.step1.description": "Découvrez les concepts fondamentaux des Organisations Agentiques et la vision stratégique",
  "howToWork.step1.cta": "Découvrir les concepts",
  "howToWork.step2.title": "Évaluer la Maturité",
  "howToWork.step2.description": "Mesurez votre préparation organisationnelle et identifiez les opportunités d'amélioration",
  "howToWork.step2.cta": "Commencer l'évaluation",
  "howToWork.step3.title": "Planifier un Atelier",
  "howToWork.step3.description": "Obtenez un plan d'action personnalisé avec nos experts pour accélérer votre transformation",
  "howToWork.step3.cta": "Planifier une consultation",
  
  // Use Cases Section
  "useCases.title": "Cas d'Usage Concrets",
  "useCases.description": "Découvrez comment d'autres organisations transforment leurs opérations avec les Organisations Agentiques",
  "useCases.case1.title": "Service Client Intelligent",
  "useCases.case1.description": "Agents IA de support automatisant les requêtes courantes tout en permettant l'escalade humaine pour les cas complexes",
  "useCases.case1.metrics": "Résultats: -40% temps de réponse, +25% satisfaction client, -30% coût opérationnel",
  "useCases.case2.title": "Direction Financière Augmentée",
  "useCases.case2.description": "Agents d'analyse financière détectant les anomalies, prédisant les tendances et optimisant les flux de trésorerie",
  "useCases.case2.metrics": "Résultats: 95% des anomalies détectées automatiquement, -20% erreurs de reporting, +15% précision prévisions",
  "useCases.case3.title": "Gestion Proactive des Risques",
  "useCases.case3.description": "Agents de monitoring continu identifiant les risques opérationnels, cybersécurité et conformité en temps réel",
  "useCases.case3.metrics": "Résultats: -60% incidents de sécurité, -50% temps de détection, +35% conformité réglementaire",
  "useCases.case4.title": "Optimisation Opérationnelle",
  "useCases.case4.description": "Agents d'optimisation automatisant les processus répétitifs et identifiant les inefficacités dans la chaîne de valeur",
  "useCases.case4.metrics": "Résultats: -25% coûts opérationnels, +30% efficacité processus, +20% productivité équipes",
  
  // Tooling & Stack Section
  "tooling.title": "Stack Technologique Agentique",
  "tooling.description": "Les grandes briques technologiques pour construire votre Organisation Agentique",
  "tooling.orchestrators.title": "Orchestrateurs d'Agents",
  "tooling.orchestrators.description": "Plateformes pour coordonner et gérer des flottes d'agents IA (AutoGen, CrewAI, LangGraph)",
  "tooling.governance.title": "Frameworks de Gouvernance",
  "tooling.governance.description": "Outils pour implémenter le cadre SAIFE: sécurité, alignement, interopérabilité, fiabilité, éthique",
  "tooling.monitoring.title": "Monitoring & Observabilité",
  "tooling.monitoring.description": "Solutions pour suivre les performances, détecter les anomalies et assurer la conformité des agents",
  "tooling.integration.title": "Intégration Entreprise",
  "tooling.integration.description": "Connecteurs et APIs pour intégrer les agents avec vos outils existants (CRM, ERP, HRIS, etc.)",
  
  // Resources Section
  "resources.title": "Ressources & Documentation",
  "resources.description": "Accédez à nos guides, whitepapers et playbooks pour approfondir vos connaissances",
  "resources.whitepaper.title": "Whitepaper: Designing Agentic Organizations",
  "resources.whitepaper.description": "Document de référence complet sur l'architecture et l'implémentation des Organisations Agentiques",
  "resources.whitepaper.cta": "Télécharger (PDF)",
  "resources.playbook.title": "Playbook: MAO en 90 jours",
  "resources.playbook.description": "Guide pratique étape par étape pour lancer votre première Organisation Agentique Minimale",
  "resources.playbook.cta": "Télécharger (PDF)",
  "resources.guide.title": "Guide: Gouvernance SAIFE",
  "resources.guide.description": "Framework détaillé pour implémenter une gouvernance IA sécurisée, alignée, interopérable, fiable et éthique",
  "resources.guide.cta": "Télécharger (PDF)",
  "resources.leadMagnet.description": "Inscrivez-vous à notre newsletter pour recevoir nos dernières ressources et insights",
  "resources.leadMagnet.placeholder": "votre.email@entreprise.com",
  "resources.leadMagnet.cta": "S'inscrire",
  
  // Quiz Section
  "quiz.badge": "Découvrez Votre Niveau",
  "quiz.title": "Mini Quiz de Maturité Agentique",
  "quiz.description": "Répondez à 5-7 questions pour obtenir un score de maturité instantané et des recommandations personnalisées",
  "quiz.feature1": "Questions rapides",
  "quiz.feature2": "Évaluation instantanée",
  "quiz.feature3": "Gratuit & confidentiel",
  "quiz.cta": "Démarrer le quiz",
  
  // Enhanced CTA Section
  "cta.assessment.title": "Ce que contient l'évaluation",
  "cta.assessment.feature1": "⏱ Durée: 10-15 minutes | Format: Quiz interactif en ligne",
  "cta.assessment.feature2": "📊 Livrable: Score de maturité sur 5 dimensions + Rapport détaillé",
  "cta.assessment.feature3": "🎯 Analyse: Benchmark sectoriel + Recommandations prioritaires",
  "cta.assessment.feature4": "💼 Suivi: Option consultation stratégique avec nos experts",
  "cta.audience.title": "À qui s'adresse l'évaluation ?",
  "cta.audience.role1": "CEO & C-Suite: Vision stratégique transformation digitale",
  "cta.audience.role2": "COO & Directeurs Opérationnels: Optimisation processus métier",
  "cta.audience.role3": "CHRO & DRH: Évolution compétences et culture organisationnelle",
  "cta.audience.role4": "CDO & Directeurs Innovation: Implémentation technologies IA",
  
  // Final CTA Section
  "finalCta.title": "Prêt à Passer à l'Action ?",
  "finalCta.description": "Commencez votre transformation agentique dès aujourd'hui avec notre évaluation gratuite ou planifiez un échange avec nos experts",
  "finalCta.button1": "Évaluer ma maturité",
  "finalCta.button2": "Planifier un échange"
};

// English translations
const en: typeof fr = {
  // Header
  "nav.about": "About",
  "nav.concepts": "Concepts",
  "nav.governance": "Governance",
  "nav.implementation": "Implementation",
  "nav.collaboration": "Collaboration",
  "nav.assessment": "Assessment",
  "nav.contact": "Contact",
  "nav.backHome": "Back to home",
  
  // Hero Section
  "hero.badge": "Organizational Transformation through AI",
  "hero.title1": "Design organizations where",
  "hero.title2": "humans and AI drive performance together",
  "hero.subtitle": "in less than 12 months",
  "hero.description": "Boost productivity by 30%, accelerate strategic decisions, reduce operational risks, and develop continuous experimentation capabilities with our agentic organizations framework.",
  "hero.cta1": "Assess your organization's agentic maturity (5 min)",
  "hero.cta2": "Discover the agentic framework",
  
  // Concepts Section
  "concepts.title": "Six Foundational Concepts",
  "concepts.description": "A comprehensive conceptual framework to understand and implement the transformation towards an Agentic Organization.",
  "concepts.ao.title": "Agentic Organization (AO)",
  "concepts.ao.description": "Organizational structure where autonomous AI agents collaborate with humans to achieve common goals.",
  "concepts.ao.plain": "In short, this transforms your organization into an intelligent network where every decision is AI-augmented, while keeping humans at the center.",
  "concepts.at.title": "Agentic Team (AT)",
  "concepts.at.description": "Work unit combining human and AI agents with complementary roles and fluid coordination.",
  "concepts.at.plain": "In short, this enables a human team to be augmented by AI agents that prepare analyses, execute repetitive tasks, and let humans focus on important decisions.",
  "concepts.amo.title": "Agentic Mode of Operation (AMO)",
  "concepts.amo.description": "Standardized protocols and processes for effective collaboration between humans and AI agents.",
  "concepts.amo.plain": "In short, this establishes clear rules of engagement so humans and AI work together frictionlessly, with well-defined processes.",
  "concepts.saife.title": "SAIFE Framework",
  "concepts.saife.description": "Governance framework for Security, Alignment, Interoperability, Reliability, and Ethics.",
  "concepts.saife.plain": "In short, this ensures your AI agents are secure, aligned with your values, compatible with your systems, reliable, and ethical.",
  "concepts.hs.title": "Humanic Skills (HS)",
  "concepts.hs.description": "Distinctly human skills essential in an AI-augmented work environment.",
  "concepts.hs.plain": "In short, this values and develops the skills that only humans possess: creativity, empathy, ethical judgment, and complex collaboration.",
  "concepts.mao.title": "Minimal Agentic Organization (MAO)",
  "concepts.mao.description": "Startup-like autonomous unit for experimenting with agentic principles in a controlled manner.",
  "concepts.mao.plain": "In short, this lets you test agentic transformation in a safe zone of your organization before scaling it broadly.",
  "concepts.level.strategic": "Strategic",
  "concepts.level.network": "Network",
  "concepts.level.agent": "Agent",
  
  // Governance Section
  "governance.title": "Multi-Level Governance Architecture",
  "governance.description": "An integrated governance structure ensuring coherence, accountability, and adaptability at all levels.",
  "governance.strategic.title": "Strategic Governance",
  "governance.strategic.description": "Definition of vision, global policies, and alignment with organizational objectives.",
  "governance.strategic.item1": "Agentic vision and mission",
  "governance.strategic.item2": "Responsible AI policies",
  "governance.strategic.item3": "Resource allocation",
  "governance.strategic.item4": "Strategic risk management",
  "governance.strategic.example": "Example: Launching a new product coordinated between R&D, Marketing and Sales with AI agents analyzing customer feedback in real-time.",
  "governance.network.title": "Network Governance",
  "governance.network.description": "Coordination of interactions between agentic teams and information flow management.",
  "governance.network.item1": "Interoperability protocols",
  "governance.network.item2": "Communication standards",
  "governance.network.item3": "Coordination mechanisms",
  "governance.network.item4": "Conflict resolution",
  "governance.network.example": "Example: Coordinating a major incident response where AI agents from IT, Communications and Support collaborate with human teams to resolve and communicate.",
  "governance.agent.title": "Agent Governance",
  "governance.agent.description": "Rules and constraints for individual behavior of AI and human agents.",
  "governance.agent.item1": "Autonomy limits",
  "governance.agent.item2": "Decision criteria",
  "governance.agent.item3": "Supervision mechanisms",
  "governance.agent.item4": "Escalation protocols",
  "governance.agent.example": "Example: A customer service AI agent automatically handles simple requests but escalates to a human when customer emotion is detected or the situation exceeds its autonomy.",
  
  // Implementation Section
  "implementation.title": "Three-Phase Implementation Strategy",
  "implementation.description": "A structured roadmap to progressively transform your organization towards an agentic model.",
  "implementation.phase1.title": "Foundations",
  "implementation.phase1.duration": "1-3 years",
  "implementation.phase1.description": "Establish the technological and cultural infrastructure necessary for transformation.",
  "implementation.phase1.item1": "Organizational readiness assessment",
  "implementation.phase1.item2": "Governance framework development",
  "implementation.phase1.item3": "Team training and awareness",
  "implementation.phase1.item4": "Pilot project selection",
  "implementation.phase2.title": "Pilot",
  "implementation.phase2.duration": "3-7 years",
  "implementation.phase2.description": "Implement limited-scope agentic systems and iterate based on feedback.",
  "implementation.phase2.item1": "MAO deployment",
  "implementation.phase2.item2": "Cross-functional team formation",
  "implementation.phase2.item3": "Monitoring systems setup",
  "implementation.phase2.item4": "Feedback collection and analysis",
  "implementation.phase3.title": "Deployment",
  "implementation.phase3.duration": "7-10 years",
  "implementation.phase3.description": "Extend agentic capabilities across the entire organization.",
  "implementation.phase3.item1": "Organizational expansion",
  "implementation.phase3.item2": "Governance hardening",
  "implementation.phase3.item3": "Continuous optimization",
  "implementation.phase3.item4": "Adaptation and evolution",
  
  // MAO Section
  "mao.badge": "Progressive Approach",
  "mao.title": "The Minimal Agentic Organization (MAO)",
  "mao.description": "The MAO is a startup-like autonomous unit operating as an experimental laboratory within the parent organization. It allows testing agentic principles against realistic organizational constraints.",
  "mao.feature1.title": "Complete Functions",
  "mao.feature1.description": "HR, Finance, Operations, Marketing, Strategy integrated",
  "mao.feature2.title": "Strategic Focus",
  "mao.feature2.description": "Three key business processes with measurable value",
  "mao.feature3.title": "Agile Approach",
  "mao.feature3.description": "Non-disruptive, iterative, and adaptive",
  "mao.cta": "Assess your readiness",
  "mao.benefits": "MAO Benefits",
  "mao.autonomy": "Operational autonomy",
  "mao.risk": "Organizational risk",
  "mao.learning": "Learning potential",
  "mao.processes": "Targeted key processes",
  
  // Collaboration Section
  "collaboration.title": "Human-AI Collaboration Spectrum",
  "collaboration.description": "The four pillars of collaborative intelligence for optimal synergy between humans and AI agents.",
  "collaboration.modes": "Collaboration Modes",
  "collaboration.humanLed": "Human-Led",
  "collaboration.humanLed.description": "Human directs, AI assists and amplifies",
  "collaboration.humanLed.example": "Ex: Manager analyzing an AI dashboard before making a strategic decision",
  "collaboration.peerToPeer": "Peer-to-Peer",
  "collaboration.peerToPeer.description": "Balanced and complementary collaboration",
  "collaboration.peerToPeer.example": "Ex: Project manager co-building a schedule with an optimization AI agent",
  "collaboration.aiLed": "AI-Led",
  "collaboration.aiLed.description": "AI directs, human supervises and validates",
  "collaboration.aiLed.example": "Ex: AI agent proposing an optimized logistics plan that human validates or adjusts",
  "collaboration.pillar1.title": "Distributed Decision Making",
  "collaboration.pillar1.description": "Decision-making power based on competence and context, not hierarchy.",
  "collaboration.pillar2.title": "Adaptive Governance",
  "collaboration.pillar2.description": "Flexible governance modes that evolve with organizational needs.",
  "collaboration.pillar3.title": "Fluid Collaboration",
  "collaboration.pillar3.description": "Seamless interaction between humans and AI with standardized protocols.",
  "collaboration.pillar4.title": "Continuous Learning",
  "collaboration.pillar4.description": "Ongoing organizational adaptation and evolution based on feedback.",
  
  // CTA Section
  "cta.title": "Ready to Transform Your Organization?",
  "cta.description": "Assess your organization's agentic maturity and get personalized recommendations for your transformation.",
  "cta.button1": "Start the assessment",
  "cta.button2": "Request a consultation",
  
  // Footer
  "footer.description": "Organizational transformation through agentic intelligence.",
  "footer.concepts": "Concepts",
  "footer.resources": "Resources",
  "footer.contact": "Contact",
  "footer.sixConcepts": "Six Foundational Concepts",
  "footer.multiLevelGovernance": "Multi-Level Governance",
  "footer.mao": "Minimal Agentic Organization",
  "footer.implementationStrategy": "Implementation Strategy",
  "footer.humanAICollaboration": "Human-AI Collaboration",
  "footer.assessmentTool": "Assessment Tool",
  "footer.requestConsultation": "Request a consultation",
  "footer.contactUs": "Contact us",
  "footer.copyright": "© 2025 AgenticOrg. All rights reserved.",
  
  // Assessment Page
  "assessment.question": "Question",
  "assessment.of": "of",
  "assessment.completed": "completed",
  "assessment.previous": "Previous",
  "assessment.next": "Next",
  "assessment.seeResults": "See results",
  "assessment.results.title": "Your Assessment Results",
  "assessment.results.subtitle": "Overall agentic maturity score",
  "assessment.results.level": "Level",
  "assessment.results.categoryTitle": "Category Analysis",
  "assessment.results.categorySubtitle": "Detail of your maturity in each area",
  "assessment.results.recommendationsTitle": "Personalized Recommendations",
  "assessment.results.recommendationsSubtitle": "Priority actions for your transformation",
  "assessment.results.restart": "Retake the assessment",
  "assessment.results.consultation": "Request a consultation",
  "assessment.level.beginner": "Beginner",
  "assessment.level.emerging": "Emerging",
  "assessment.level.progressing": "Progressing",
  "assessment.level.advanced": "Advanced",
  "assessment.level.beginner.description": "Your organization is at the beginning of its journey towards agentic transformation. Important foundations need to be established.",
  "assessment.level.emerging.description": "Your organization has started its transformation but needs to strengthen its foundations to progress effectively.",
  "assessment.level.progressing.description": "Your organization is progressing well towards agentic maturity. Focus on expansion and optimization.",
  "assessment.level.advanced.description": "Your organization is well positioned for a complete agentic transformation.",
  "assessment.category.culture": "Organizational Culture",
  "assessment.category.tech": "Technological Infrastructure",
  "assessment.category.governance": "Governance",
  "assessment.category.skills": "Skills",
  "assessment.category.collaboration": "Collaboration",
  "assessment.q1": "How does your organization perceive artificial intelligence?",
  "assessment.q1.o1": "As a threat to employment",
  "assessment.q1.o2": "As one technical tool among others",
  "assessment.q1.o3": "As a potential partner to improve productivity",
  "assessment.q1.o4": "As a strategic collaborator for transformation",
  "assessment.q2": "What is the level of openness to change in your organization?",
  "assessment.q2.o1": "Strong resistance to change",
  "assessment.q2.o2": "Passive acceptance of imposed changes",
  "assessment.q2.o3": "Proactive adaptation to new methods",
  "assessment.q2.o4": "Culture of continuous innovation and experimentation",
  "assessment.q3": "What is the state of your current technological infrastructure?",
  "assessment.q3.o1": "Isolated and poorly integrated legacy systems",
  "assessment.q3.o2": "Partially modernized infrastructure",
  "assessment.q3.o3": "Cloud infrastructure with APIs and integrations",
  "assessment.q3.o4": "Modern, scalable, AI-ready architecture",
  "assessment.q4": "How do you manage your organizational data?",
  "assessment.q4.o1": "Scattered and unstructured data",
  "assessment.q4.o2": "Some centralized databases",
  "assessment.q4.o3": "Data warehouse with basic governance",
  "assessment.q4.o4": "Unified data platform with mature governance",
  "assessment.q5": "Do you have AI governance policies?",
  "assessment.q5.o1": "No policies in place",
  "assessment.q5.o2": "Some informal guidelines",
  "assessment.q5.o3": "Documented policies being deployed",
  "assessment.q5.o4": "Complete and applied AI governance framework",
  "assessment.q6": "How are strategic decisions made in your organization?",
  "assessment.q6.o1": "Centralized decisions at the top only",
  "assessment.q6.o2": "Limited delegation with hierarchical validation",
  "assessment.q6.o3": "Distributed decisions with governance framework",
  "assessment.q6.o4": "Adaptive decision-making based on competencies",
  "assessment.q7": "What is the level of AI skills in your organization?",
  "assessment.q7.o1": "Very few AI skills available",
  "assessment.q7.o2": "Some isolated experts",
  "assessment.q7.o3": "Dedicated AI teams and training programs",
  "assessment.q7.o4": "AI skills integrated at all levels",
  "assessment.q8": "How do you develop humanic skills (creativity, empathy, judgment)?",
  "assessment.q8.o1": "No particular focus on these skills",
  "assessment.q8.o2": "Occasional training available",
  "assessment.q8.o3": "Structured development programs",
  "assessment.q8.o4": "Continuous learning culture and explicit valorization",
  "assessment.q9": "How do your teams currently collaborate with AI tools?",
  "assessment.q9.o1": "Minimal or non-existent use",
  "assessment.q9.o2": "Individual and uncoordinated use",
  "assessment.q9.o3": "Defined processes for certain tasks",
  "assessment.q9.o4": "Human-AI collaboration integrated into workflows",
  "assessment.q10": "Have you experimented with pilot projects involving AI?",
  "assessment.q10.o1": "No pilot projects",
  "assessment.q10.o2": "Some isolated experiments",
  "assessment.q10.o3": "Structured pilot projects with feedback",
  "assessment.q10.o4": "Continuous innovation program with scaling of successes",
  
  // Contact Page
  "contact.title": "Request a Consultation",
  "contact.description": "Our experts support you in your transformation towards an Agentic Organization. Fill out the form below to be contacted.",
  "contact.whyTitle": "Why contact us?",
  "contact.reason1.title": "Personalized diagnosis",
  "contact.reason1.description": "In-depth analysis of your organization",
  "contact.reason2.title": "Roadmap",
  "contact.reason2.description": "Action plan tailored to your objectives",
  "contact.reason3.title": "Expert support",
  "contact.reason3.description": "Continuous support in your transformation",
  "contact.guarantee.title": "Fast response guaranteed",
  "contact.guarantee.description": "Our team commits to responding within 24-48 business hours to schedule an initial discussion.",
  "contact.form.title": "Contact Form",
  "contact.form.required": "All fields marked with * are required",
  "contact.form.name": "Full name",
  "contact.form.email": "Professional email",
  "contact.form.company": "Company",
  "contact.form.role": "Position",
  "contact.form.interest": "Subject of interest",
  "contact.form.message": "Message",
  "contact.form.submit": "Send my request",
  "contact.form.sending": "Sending...",
  "contact.form.selectSubject": "Select a subject",
  "contact.form.interest.diagnostic": "Agentic maturity diagnosis",
  "contact.form.interest.strategy": "Transformation strategy",
  "contact.form.interest.mao": "MAO implementation",
  "contact.form.interest.governance": "AI Governance",
  "contact.form.interest.training": "Team training",
  "contact.form.interest.other": "Other",
  "contact.form.namePlaceholder": "John Smith",
  "contact.form.emailPlaceholder": "john.smith@company.com",
  "contact.form.companyPlaceholder": "Your company name",
  "contact.form.rolePlaceholder": "Director / Manager / etc.",
  "contact.form.messagePlaceholder": "Briefly describe your project or questions...",
  "contact.success.title": "Request Sent!",
  "contact.success.description": "Thank you for your interest. Our team will contact you within 24-48 hours.",
  "contact.success.cta": "In the meantime, you can explore our assessment tool to better understand your organization's agentic maturity.",
  "contact.success.assessment": "Take the assessment",
  "contact.error.required": "Please fill in all required fields",
  "contact.error.generic": "An error occurred. Please try again.",
  "contact.success.toast": "Your request has been sent successfully!",
  "assessment.saved": "Results saved successfully",
  
  // How to Work Section
  "howToWork.title": "How to Work With Us?",
  "howToWork.description": "A structured three-step approach to transform your organization",
  "howToWork.step1.title": "Understand the Framework",
  "howToWork.step1.description": "Discover the fundamental concepts of Agentic Organizations and the strategic vision",
  "howToWork.step1.cta": "Discover concepts",
  "howToWork.step2.title": "Assess Maturity",
  "howToWork.step2.description": "Measure your organizational readiness and identify improvement opportunities",
  "howToWork.step2.cta": "Start assessment",
  "howToWork.step3.title": "Schedule a Workshop",
  "howToWork.step3.description": "Get a personalized action plan with our experts to accelerate your transformation",
  "howToWork.step3.cta": "Schedule consultation",
  
  // Use Cases Section
  "useCases.title": "Real-World Use Cases",
  "useCases.description": "Discover how other organizations are transforming their operations with Agentic Organizations",
  "useCases.case1.title": "Intelligent Customer Service",
  "useCases.case1.description": "AI support agents automating routine queries while enabling human escalation for complex cases",
  "useCases.case1.metrics": "Results: -40% response time, +25% customer satisfaction, -30% operational cost",
  "useCases.case2.title": "Augmented Finance Department",
  "useCases.case2.description": "Financial analysis agents detecting anomalies, predicting trends, and optimizing cash flow",
  "useCases.case2.metrics": "Results: 95% anomalies detected automatically, -20% reporting errors, +15% forecast accuracy",
  "useCases.case3.title": "Proactive Risk Management",
  "useCases.case3.description": "Continuous monitoring agents identifying operational risks, cybersecurity, and compliance in real-time",
  "useCases.case3.metrics": "Results: -60% security incidents, -50% detection time, +35% regulatory compliance",
  "useCases.case4.title": "Operational Optimization",
  "useCases.case4.description": "Optimization agents automating repetitive processes and identifying inefficiencies in the value chain",
  "useCases.case4.metrics": "Results: -25% operational costs, +30% process efficiency, +20% team productivity",
  
  // Tooling & Stack Section
  "tooling.title": "Agentic Technology Stack",
  "tooling.description": "The key technology building blocks to construct your Agentic Organization",
  "tooling.orchestrators.title": "Agent Orchestrators",
  "tooling.orchestrators.description": "Platforms to coordinate and manage fleets of AI agents (AutoGen, CrewAI, LangGraph)",
  "tooling.governance.title": "Governance Frameworks",
  "tooling.governance.description": "Tools to implement the SAIFE framework: security, alignment, interoperability, reliability, ethics",
  "tooling.monitoring.title": "Monitoring & Observability",
  "tooling.monitoring.description": "Solutions to track performance, detect anomalies, and ensure agent compliance",
  "tooling.integration.title": "Enterprise Integration",
  "tooling.integration.description": "Connectors and APIs to integrate agents with your existing tools (CRM, ERP, HRIS, etc.)",
  
  // Resources Section
  "resources.title": "Resources & Documentation",
  "resources.description": "Access our guides, whitepapers, and playbooks to deepen your knowledge",
  "resources.whitepaper.title": "Whitepaper: Designing Agentic Organizations",
  "resources.whitepaper.description": "Comprehensive reference document on the architecture and implementation of Agentic Organizations",
  "resources.whitepaper.cta": "Download (PDF)",
  "resources.playbook.title": "Playbook: MAO in 90 Days",
  "resources.playbook.description": "Practical step-by-step guide to launch your first Minimal Agentic Organization",
  "resources.playbook.cta": "Download (PDF)",
  "resources.guide.title": "Guide: SAIFE Governance",
  "resources.guide.description": "Detailed framework for implementing secure, aligned, interoperable, reliable, and ethical AI governance",
  "resources.guide.cta": "Download (PDF)",
  "resources.leadMagnet.description": "Subscribe to our newsletter to receive our latest resources and insights",
  "resources.leadMagnet.placeholder": "your.email@company.com",
  "resources.leadMagnet.cta": "Subscribe",
  
  // Quiz Section
  "quiz.badge": "Discover Your Level",
  "quiz.title": "Agentic Maturity Mini Quiz",
  "quiz.description": "Answer 5-7 questions to get an instant maturity score and personalized recommendations",
  "quiz.feature1": "Quick questions",
  "quiz.feature2": "Instant assessment",
  "quiz.feature3": "Free & confidential",
  "quiz.cta": "Start the quiz",
  
  // Enhanced CTA Section
  "cta.assessment.title": "What the assessment includes",
  "cta.assessment.feature1": "⏱ Duration: 10-15 minutes | Format: Interactive online quiz",
  "cta.assessment.feature2": "📊 Deliverable: Maturity score on 5 dimensions + Detailed report",
  "cta.assessment.feature3": "🎯 Analysis: Sector benchmark + Priority recommendations",
  "cta.assessment.feature4": "💼 Follow-up: Strategic consultation option with our experts",
  "cta.audience.title": "Who is the assessment for?",
  "cta.audience.role1": "CEO & C-Suite: Strategic vision for digital transformation",
  "cta.audience.role2": "COO & Operations Directors: Business process optimization",
  "cta.audience.role3": "CHRO & HR Directors: Skills and organizational culture evolution",
  "cta.audience.role4": "CDO & Innovation Directors: AI technology implementation",
  
  // Final CTA Section
  "finalCta.title": "Ready to Take Action?",
  "finalCta.description": "Start your agentic transformation today with our free assessment or schedule a call with our experts",
  "finalCta.button1": "Assess my maturity",
  "finalCta.button2": "Schedule a call"
};

const translations = { fr, en };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language") as Language;
      if (saved && (saved === "fr" || saved === "en")) {
        return saved;
      }
      // Detect browser language
      const browserLang = navigator.language.split("-")[0];
      return browserLang === "en" ? "en" : "fr";
    }
    return "fr";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
